### ISSUE TITLE
insert_add_column_or_create_table.rb:9:in `unprepend': private method `split' called for #<Array:0x1011e9d60> (NoMethodError)

### ISSUE THREAD

**Issue by mirrorwis** [drnic/ruby-on-rails-tmbundle#18]
/Users/Andy/Library/Application Support/TextMate/Pristine Copy/Bundles/Ruby on Rails.tmbundle/Support/bin/insert_add_column_or_create_table.rb:9:in `unprepend': private method`split' called for #Array:0x1011e9d60 (NoMethodError)
    from /Users/Andy/Library/Application Support/TextMate/Pristine Copy/Bundles/Ruby on Rails.tmbundle/Support/bin/insert_add_column_or_create_table.rb:54

RVM 1.8.7
Rails 2.3.8

**Comment by wulffeld** [comment]
Changing the unprepend method to:

```
def unprepend(text, prefix)
  text.map { |line| line.index(prefix) == 0 ? line.sub(prefix, '') : line }.join
end
```

seems to fix the bug.

**Comment by bquorning** [comment]
Thanks wulffeld, fixed the issue here as well :-)

**Comment by mtodd** [comment]
Same as well. Has not been merged into master but should.

I might just add this in there, though:

```
text = text.split("\n") if text.responds_to?(:split)
```

**Comment by michaelkoper** [comment]
Thanks this fixed it for me too.

Rails 2.1
Ruby 1.8.7
