### ISSUE TITLE
Failure running "Quick Migration"

### ISSUE THREAD

**Issue by zmillman** [drnic/ruby-on-rails-tmbundle#52]
I get the following error dialog when trying to use Quick Migration:

```
/Users/zachmillman/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rails/text_mate.rb:54:in `method_missing': undefined method `filepath' for TextMate:Module (NoMethodError)
    from /Users/zachmillman/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rails/rails_path.rb:54:in `initialize'
    from /Users/zachmillman/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/bin/generate_quick_migration.rb:26:in `new'
    from /Users/zachmillman/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/bin/generate_quick_migration.rb:26
```

**Comment by marcusramberg** [comment]
+1 I also have problems with this. My error is 

```
/Users/marcus/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:371:in `to_plist': An object in the argument tree could not be converted (ArgumentError)
    from /Users/marcus/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:371:in `request_string_core'
    from /Users/marcus/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:209:in `request_string'
    from /Users/marcus/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/bin/generate_quick_migration.rb:14:in `<main>'
```

**Comment by IamNaN** [comment]
I'm having it too, especially when running scripts like create-partial-from-selection. I suspect this is caused by TM wanting a ruby method deprecated after v 1.8, but am wondering if this bundle is even still being maintained given its last update.
