### ISSUE TITLE
Create Partial from Selection not working

### ISSUE THREAD

**Issue by jeremybdk** [drnic/ruby-on-rails-tmbundle#53]
HI,
I am new to textmate but I am having some issues getting create partial from selection working : here is the error I am having 

/Users/jeremy/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:355:in `to_plist': An object in the argument tree could not be converted (ArgumentError)
    from /Users/jeremy/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:355:in`request_string_core'
    from /Users/jeremy/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:193:in `request_string'
    from /Users/jeremy/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:24:in`<main>'

I have been spending the last hour trying to fix it without any luck.

I am running TextMate 2.0 with Ruby 1.9.3 and OS X 10.8.3

Thanks in advance,

**Comment by jeremybdk** [comment]
I ended up getting that working with setting TM_RUBY to /usr/bin/ruby but that use the default ruby version 1.8.7 on my mac. Is that correct ?

Thanks
